#include <stdio.h>

int main()
{
    unsigned char L, K1, K2;
    unsigned char Rb = 0x87;

    printf("Enter encrypted zero block (L) in hexadecimal (00-FF): ");
    scanf("%hhx", &L);

    // Generate K1
    if (L & 0x80)
        K1 = (L << 1) ^ Rb;
    else
        K1 = (L << 1);

    // Generate K2
    if (K1 & 0x80)
        K2 = (K1 << 1) ^ Rb;
    else
        K2 = (K1 << 1);

    printf("\nEncrypted Zero Block (L) = %02X", L);
    printf("\nSubkey K1 = %02X", K1);
    printf("\nSubkey K2 = %02X", K2);

    printf("\n\nConclusion:");
    printf("\nK1 is generated by left shifting L by one bit.");
    printf("\nIf the MSB is 1, XOR with constant Rb (0x87).");
    printf("\nK2 is generated similarly from K1.");

    return 0;
}
